name: Auto Merge Action

on: pull_request

jobs:
  enable-auto-merge:
    runs-on: ubuntu-latest
    steps:
    - uses: alexwilson/enable-github-automerge-action@main
      with:
        github-token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
