name: Auto Merge

on:
  check_suite:
    types: 
      - completed

jobs:
  auto-merge-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Run Auto Merge
        env:
          GH_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          BRANCH_NAME: ${{ github.ref_name }}
        run: |
          python3 auto-merge.py
